/**
 * Correspondance entre les noms d'icones utilises dans le dashboard
 * (Material Symbols, Lucide/Feather, Phosphor) et les icones Papicons.
 *
 * Un nom absent de cette table est converti en PascalCase par toPapiconsName,
 * puis rendu par Lucide si Papicons ne le fournit pas.
 */
export const iconAliases: Record<string, string> = {
  'alert-triangle': 'AlertTriangle',
  'gavel': 'Gavel',
  'policy': 'Lock',
  'admin_panel_settings': 'Lock',
  'book': 'Paper',
  'settings': 'Gears',
  'search': 'Search',
  'radar': 'Search',
  'chartlineup': 'TrendingUp',
  'chatcircledots': 'MessageCircle',
  'microphone': 'Mic',
  'usersfour': 'Users',
  'shieldwarning': 'ShieldAlert',
  'shieldcheck': 'ShieldCheck',
  'mailopen': 'MailOpen',
  'chartpieslice': 'PieChart',
  'lightning': 'Zap',
  'alert-octagon': 'AlertOctagon',
  'close': 'Cross',
  'x': 'Cross',
  'delete': 'Trash',
  'edit': 'Pen',
  'forum': 'TextBubble',
  'check_circle': 'Check',
  'cancel': 'Add',
  'error': 'AlertCircle',
  'warning': 'AlertTriangle',
  'info': 'Info',
  'help': 'Info',
  'notifications': 'Bell',
  'mail': 'Mail',
  'person': 'User',
  'group': 'User',
  'add': 'Plus',
  'remove': 'Minus',
  'arrow_forward': 'ArrowRight',
  'arrow_back': 'ArrowLeft',
  'expand_more': 'ChevronDown',
  'expand_less': 'ChevronUp',
  'chevron_right': 'ChevronRight',
  'chevron_left': 'ChevronLeft',
  'menu': 'Menu',
  'more_vert': 'Menu',
  'more_horiz': 'Menu',
  'refresh': 'Gears',
  'sync': 'Gears',
  'cloud_upload': 'ArrowUp',
  'cloud_download': 'ArrowDown',
  'visibility': 'Camera', // No Eye in Papicons
  'visibility_off': 'Camera',
  'lock': 'Lock',
  'lock_open': 'Unlock',
  'key': 'Lock',
  'terminal': 'Code',
  'code': 'Code',
  'database': 'Grid',
  'server': 'Gears',
  'history': 'Clock',
  'timer': 'Clock',
  'schedule': 'Calendar',
  'event': 'Calendar',
  'dashboard': 'Grid',
  'analytics': 'Grades',
  'pie_chart': 'Pie',
  'show_chart': 'ArrowRightUp',
  'star': 'Star',
  'favorite': 'Heart',
  'thumb_up': 'Check',
  'thumb_down': 'Minus',
  'share': 'ExternalLink',
  'download': 'ArrowDown',
  'upload': 'ArrowUp',
  'link': 'Link',
  'logout': 'Logout',
  'login': 'Login',
  'account_circle': 'User',
  'verified': 'Check',
  'verified_user': 'User',
  'shield': 'Lock',
  'security': 'Lock',
  'block': 'UserCross',
  'robot': 'Gears',
  'robot_2': 'Gears',
  'bot': 'Gears',
  'person_add_disabled': 'UserCross',
  'how_to_reg': 'User',
  'chat': 'TextBubble',
  'message-square': 'TextBubble',
  'external-link': 'ExternalLink',
  'trash': 'Trash',
  'trash-2': 'Trash',
  'edit-2': 'Pen',
  'plus': 'Plus',
  'plus-circle': 'Plus',
  'minus-circle': 'Minus',
  'alert-circle': 'AlertCircle',
  'help-circle': 'Info',
  'bell': 'Bell',
  'bell-off': 'Bell',
  'calendar': 'Calendar',
  'clock': 'Clock',
  'user': 'User',
  'users': 'User',
  'user-plus': 'User',
  'user-minus': 'UserCross',
  'shield-off': 'Lock',
  'file-text': 'Paper',
  'copy': 'Paper',
  'save': 'Paper',
  'refresh-cw': 'Gears',
  'refresh-ccw': 'Gears',
  'loader': 'Gears',
  'loader-2': 'Gears',
  'activity': 'Grades',
  'trending-up': 'ArrowRightUp',
  'trending-down': 'ArrowRightDown',
  'pie-chart': 'Pie',
  'bar-chart': 'Grades',
  'bar-chart-2': 'Grades',
  'layers': 'Grid',
  'grid': 'Grid',
  'command': 'Code',
  'cpu': 'Gears',
  'hard-drive': 'Grid',
  'layout': 'Grid',
  'image': 'Gallery',
  'video': 'Gallery',
  'music': 'Gallery',
  'mic': 'Gallery',
  'volume-2': 'Gallery',
  'volume-x': 'Gallery',
  'camera': 'Camera',
  'eye': 'Camera',
  'eye-off': 'Camera',
  'link-2': 'Link',
  'unlink': 'Link',
  'globe': 'Globe',
  'map-pin': 'MapPin',
  'navigation': 'MapPin',
  'phone': 'Phone',
  'send': 'ArrowRightUp',
  'log-out': 'Logout',
  'log-in': 'Login',
  'more-vertical': 'Menu',
  'more-horizontal': 'Menu',
  'chevron-down': 'ChevronDown',
  'chevron-up': 'ChevronUp',
  'chevron-left': 'ChevronLeft',
  'chevron-right': 'ChevronRight',
  'arrow-down': 'ArrowDown',
  'arrow-up': 'ArrowUp',
  'arrow-left': 'ArrowLeft',
  'arrow-right': 'ArrowRight',
  'minus': 'Minus',
  'crosshair': 'Plus',
  'maximize': 'ArrowRightUpBox',
  'minimize': 'ArrowLeftDownBox',
  'check': 'Check',
  'check-circle': 'Check',
  'circle': 'Circle',
  'square': 'Square',
  'triangle': 'Triangle',
  'crown': 'Crown',
  'heart': 'Heart',
  'moon': 'Moon',
  'sun': 'Sun',
  'cloud': 'Cloud',
  'zap': 'Sparkles',
  'sparkles': 'Sparkles',
  'edit-3': 'Pen',
  'clipboard': 'Paper',
  'book-open': 'Paper',
  'bookmark': 'Bookmark',
  'tag': 'Bookmark',
  'hash': 'Bookmark',
  'gift': 'Gift',
  'shopping-bag': 'ShoppingBag',
  'shopping-cart': 'ShoppingCart',
  'credit-card': 'Card',
  'wallet': 'Card',
  'dollar-sign': 'DollarSign',
  'euro-sign': 'Euro',
  'github': 'Butterfly',
  'twitter': 'Butterfly',
  'facebook': 'Butterfly',
  'instagram': 'Gallery',
  'linkedin': 'User',
  'slack': 'TextBubble',
  'youtube': 'Gallery',
  'twitch': 'Gallery',
  'package': 'Grid',
  'box': 'Grid',
  'unlock': 'Unlock',
  'flag': 'Bookmark',
  'hammer': 'Gears',
  'wrench': 'Gears',
  'briefcase': 'Paper',
  'tool': 'Gears',
  'gears': 'Gears',
  'cog': 'Gears',
  'coffee': 'Coffee',
  'utility-pole': 'UtilityPole',
  'pending_actions': 'Clock',
  'rss_feed': 'Globe',
  'extension': 'Grid',
  'hub': 'ExternalLink',
  'bolt': 'Sparkles',
  'api': 'Code',
  'bug_report': 'Alert',
  'notifications_active': 'Bell',
  'discord': 'Butterfly',
  // Phosphor-style / legacy names that otherwise fell back to the "?" HelpCircle icon
  'arrowsquareout': 'ExternalLink',
  'arrowsclockwise': 'RefreshCw',
  'calendarblank': 'Calendar',
  'calendardots': 'CalendarDays',
  'caretdown': 'ChevronDown',
  'caretleft': 'ChevronLeft',
  'caretright': 'ChevronRight',
  'chart': 'BarChart3',
  'cloudarrowup': 'UploadCloud',
  'downloadsimple': 'Download',
  'filexls': 'FileSpreadsheet',
  'fire': 'Flame',
  'gear': 'Settings',
  'heartbeat': 'HeartPulse',
  'listbullets': 'List',
  'magnifyingglass': 'Search',
  'paperplanetilt': 'Send',
  'pencilsimple': 'Pencil',
  'textbubble': 'TextBubble',
  'trendup': 'TrendingUp',
  'userfocus': 'UserCheck',
  'account_tree': 'Network',
  'add_circle': 'PlusCircle',
  'assignment': 'ClipboardList',
  'assignment_turned_in': 'ClipboardCheck',
  'channel': 'Hash',
  'content_copy': 'Copy',
  'description': 'FileText',
  'drag_indicator': 'GripVertical',
  'edit_note': 'SquarePen',
  'hashtag': 'Hash',
  'message': 'MessageSquare',
  'notes': 'StickyNote',
  'people': 'Users',
  'person-add': 'UserPlus',
  'role': 'Shield',
  'schema': 'Workflow',
  'work': 'Briefcase',
  'banning': 'Ban',
  'calendarslash': 'CalendarOff',
  'chatbubbles': 'MessagesSquare',
  'gamecontroller': 'Gamepad2',
  'userlist': 'Users',
  'usersthree': 'Users',
  'arrow_drop_down_circle': 'ChevronDown',
  'calendar_today': 'Calendar',
  'check_box': 'CheckSquare',
  'email': 'Mail',
  'grid_on': 'LayoutGrid',
  'grid_view': 'LayoutGrid',
  'linear_scale': 'SlidersHorizontal',
  'radio_button_checked': 'CircleDot',
  'short_text': 'Type',
  'title': 'Heading',
  'translate': 'Languages',
  'tune': 'SlidersHorizontal',

  // Noms Phosphor ecrits en CamelCase : toPapiconsName rabaisse la casse de
  // tout ce qui suit la premiere lettre ('SpeakerHigh' -> 'Speakerhigh'), donc
  // sans alias ils ne resolvaient nulle part et tombaient sur HelpCircle.
  'speakerhigh': 'Volume2',
  'sortascending': 'ArrowUpNarrowWide',
  'sortdescending': 'ArrowDownWideNarrow',
  'chevronup': 'ChevronUp',
  'arrowsin': 'Minimize2',
  'arrowsout': 'Maximize2',
  'arrowscounterclockwise': 'RotateCcw',
  'warningcircle': 'AlertCircle',
  'prohibit': 'Ban',

  // Noms Material Symbols encore presents dans quelques pages.
  'report_problem': 'AlertTriangle',
  'filter_list_off': 'FunnelX',
  'progress_activity': 'Gears',

  // Absents du registre Lucide du dashboard jusqu'ici.
  'chevrons-right': 'ChevronsRight',
  'toggle-left': 'ToggleLeft',
  'sort-asc': 'ArrowUpNarrowWide',
  'sort-desc': 'ArrowDownWideNarrow',

  // Noms en CamelCase que la normalisation aplatit ('CreditCard' devient
  // 'Creditcard'), donc introuvables sans alias explicite.
  'creditcard': 'Card',
  'arrowdownbox': 'ArrowDownBox',
  'trianglealert': 'AlertTriangle',
  'imageoff': 'ImageOff',
  'messagesquareoff': 'MessageSquareOff',
  'fingerprint': 'FingerprintPattern',
  'sliders': 'SlidersHorizontal',
  'fishing': 'Fish',
  'undo': 'RotateCcw',
  'trenddown': 'TrendingDown'
};

export const fallbackIconName = 'Grid';

/** Resout un nom d'icone quelconque en nom Papicons/Lucide (PascalCase). */
export function toPapiconsName(value: unknown): string {
  const normalized = typeof value === 'string' ? value.trim() : '';
  if (!normalized) return fallbackIconName;

  const alias = iconAliases[normalized.toLowerCase()];
  if (alias) return alias;

  return normalized
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1).toLowerCase())
    .join('');
}
